### ISSUE TITLE
How to run testclient.cc

### ISSUE THREAD

**Issue by Xandao89** [RoboCup-SSL/ssl-refbox#38]
hello,

What do I need to do to run testclient.cc, to receive the data from Referee Box?

**Comment by Xandao89** [comment]
Great,

I already ran the program in my PC,
I have another doubt, is possible I copy some functions of testclient.cc ,  and transfer them to my program ¨main.cpp¨ inside of Ssl_Vision/bin/client, to receive in ¨main.cpp¨ all the SSL_Vision information, and the Referee_box information in a only program?

**Comment by Hawk777** [comment]
Sure. Most people want to receive both the vision data and the refbox data at the same time. You’ll probably want to use either some sort of event system (whatever toolkit you’re using probably has one built in, otherwise `select` or `poll` are appropriate if you’re using Linux) or else use multiple threads, since you can’t receive from both sockets at the same time.
